meta_product_name: "Abiona"
meta_title: "Abiona - Your travel agent for the future"
meta_description: "Abiona helps you design your dream safari online. Tell us what you like and we’ll recommend a custom adventure :elefante:"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards